// ─── Triolingo curriculum ────────────────────────────────────────────────
// Speaking-first Mandarin. Pinyin is space-separated per syllable so the
// app can derive tones. type: "w" = word, "p" = phrase/sentence.

const UNITS = [
  { n: 1,  name: "First Words",       emoji: "👋", tag: "Greet anyone with confidence" },
  { n: 2,  name: "Numbers",           emoji: "🔢", tag: "Count, bargain, survive" },
  { n: 3,  name: "About Me",          emoji: "🙋", tag: "Introduce yourself" },
  { n: 4,  name: "Family & Friends",  emoji: "🧡", tag: "Talk about your people" },
  { n: 5,  name: "This & That",       emoji: "👉", tag: "Point at things and ask" },
  { n: 6,  name: "Food & Drink",      emoji: "🍜", tag: "Order like a local" },
  { n: 7,  name: "Time",              emoji: "🕐", tag: "Days, hours, plans" },
  { n: 8,  name: "Getting Around",    emoji: "🚕", tag: "Never get lost" },
  { n: 9,  name: "Shopping",          emoji: "🛍️", tag: "Haggle happily" },
  { n: 10, name: "Daily Life",        emoji: "☀️", tag: "Say what you do" },
  { n: 11, name: "Feelings",          emoji: "😊", tag: "Say how you feel" },
  { n: 12, name: "Conversation Glue", emoji: "🧩", tag: "Sound natural" },
];

const VOCAB = [
  // ── Unit 1 · First Words ──────────────────────────────────────────
  { id:"u1-1",  unit:1, type:"w", hanzi:"你好",   pinyin:"nǐ hǎo",  en:"hello" },
  { id:"u1-2",  unit:1, type:"w", hanzi:"谢谢",   pinyin:"xiè xie", en:"thank you" },
  { id:"u1-3",  unit:1, type:"w", hanzi:"不客气", pinyin:"bú kè qi", en:"you're welcome" },
  { id:"u1-4",  unit:1, type:"w", hanzi:"对不起", pinyin:"duì bu qǐ", en:"sorry" },
  { id:"u1-5",  unit:1, type:"w", hanzi:"没关系", pinyin:"méi guān xi", en:"it's okay / no worries" },
  { id:"u1-6",  unit:1, type:"w", hanzi:"再见",   pinyin:"zài jiàn", en:"goodbye" },
  { id:"u1-7",  unit:1, type:"w", hanzi:"请",     pinyin:"qǐng",    en:"please" },
  { id:"u1-8",  unit:1, type:"w", hanzi:"好",     pinyin:"hǎo",     en:"good / okay" },
  { id:"u1-9",  unit:1, type:"w", hanzi:"是",     pinyin:"shì",     en:"to be / yes", note:"The all-purpose “is/am/are”. Also works as “yes”." },
  { id:"u1-10", unit:1, type:"w", hanzi:"不",     pinyin:"bù",      en:"no / not", note:"Put 不 before anything to negate it: 不好 = not good." },
  { id:"u1-11", unit:1, type:"p", hanzi:"你好吗？", pinyin:"nǐ hǎo ma", en:"how are you?" },
  { id:"u1-12", unit:1, type:"p", hanzi:"我很好",  pinyin:"wǒ hěn hǎo", en:"I'm very good" },
  { id:"u1-13", unit:1, type:"p", hanzi:"你呢？",  pinyin:"nǐ ne",   en:"and you?" },
  { id:"u1-14", unit:1, type:"p", hanzi:"早上好",  pinyin:"zǎo shang hǎo", en:"good morning" },
  { id:"u1-15", unit:1, type:"w", hanzi:"晚安",   pinyin:"wǎn ān",  en:"good night" },
  { id:"u1-16", unit:1, type:"p", hanzi:"明天见",  pinyin:"míng tiān jiàn", en:"see you tomorrow" },

  // ── Unit 2 · Numbers ──────────────────────────────────────────────
  { id:"u2-1",  unit:2, type:"w", hanzi:"一",   pinyin:"yī",   en:"one" },
  { id:"u2-2",  unit:2, type:"w", hanzi:"二",   pinyin:"èr",   en:"two" },
  { id:"u2-3",  unit:2, type:"w", hanzi:"三",   pinyin:"sān",  en:"three" },
  { id:"u2-4",  unit:2, type:"w", hanzi:"四",   pinyin:"sì",   en:"four" },
  { id:"u2-5",  unit:2, type:"w", hanzi:"五",   pinyin:"wǔ",   en:"five" },
  { id:"u2-6",  unit:2, type:"w", hanzi:"六",   pinyin:"liù",  en:"six" },
  { id:"u2-7",  unit:2, type:"w", hanzi:"七",   pinyin:"qī",   en:"seven" },
  { id:"u2-8",  unit:2, type:"w", hanzi:"八",   pinyin:"bā",   en:"eight" },
  { id:"u2-9",  unit:2, type:"w", hanzi:"九",   pinyin:"jiǔ",  en:"nine" },
  { id:"u2-10", unit:2, type:"w", hanzi:"十",   pinyin:"shí",  en:"ten" },
  { id:"u2-11", unit:2, type:"w", hanzi:"零",   pinyin:"líng", en:"zero" },
  { id:"u2-12", unit:2, type:"w", hanzi:"百",   pinyin:"bǎi",  en:"hundred" },
  { id:"u2-13", unit:2, type:"w", hanzi:"两",   pinyin:"liǎng", en:"two (of something)", note:"Counting things? Use 两, not 二: 两个 = two of them." },
  { id:"u2-14", unit:2, type:"w", hanzi:"几",   pinyin:"jǐ",   en:"how many" },
  { id:"u2-15", unit:2, type:"w", hanzi:"多少", pinyin:"duō shao", en:"how much / how many" },
  { id:"u2-16", unit:2, type:"p", hanzi:"十五", pinyin:"shí wǔ", en:"fifteen", note:"Numbers stack: ten-five = 15. Chinese numbers are beautifully logical." },
  { id:"u2-17", unit:2, type:"p", hanzi:"二十三", pinyin:"èr shí sān", en:"twenty-three" },
  { id:"u2-18", unit:2, type:"p", hanzi:"一百块", pinyin:"yì bǎi kuài", en:"one hundred yuan" },

  // ── Unit 3 · About Me ─────────────────────────────────────────────
  { id:"u3-1",  unit:3, type:"w", hanzi:"我",   pinyin:"wǒ",   en:"I / me" },
  { id:"u3-2",  unit:3, type:"w", hanzi:"你",   pinyin:"nǐ",   en:"you" },
  { id:"u3-3",  unit:3, type:"w", hanzi:"他",   pinyin:"tā",   en:"he / him" },
  { id:"u3-4",  unit:3, type:"w", hanzi:"她",   pinyin:"tā",   en:"she / her", note:"He and she sound identical in spoken Chinese — context does the work." },
  { id:"u3-5",  unit:3, type:"w", hanzi:"我们", pinyin:"wǒ men", en:"we / us", note:"们 makes pronouns plural: 我→我们, 你→你们." },
  { id:"u3-6",  unit:3, type:"w", hanzi:"叫",   pinyin:"jiào", en:"to be called" },
  { id:"u3-7",  unit:3, type:"w", hanzi:"名字", pinyin:"míng zi", en:"name" },
  { id:"u3-8",  unit:3, type:"w", hanzi:"什么", pinyin:"shén me", en:"what" },
  { id:"u3-9",  unit:3, type:"w", hanzi:"人",   pinyin:"rén",  en:"person" },
  { id:"u3-10", unit:3, type:"w", hanzi:"中国", pinyin:"zhōng guó", en:"China" },
  { id:"u3-11", unit:3, type:"w", hanzi:"中文", pinyin:"zhōng wén", en:"Chinese (language)" },
  { id:"u3-12", unit:3, type:"w", hanzi:"岁",   pinyin:"suì",  en:"years old" },
  { id:"u3-13", unit:3, type:"p", hanzi:"你叫什么名字？", pinyin:"nǐ jiào shén me míng zi", en:"what's your name?", note:"Question words stay in place — no word-order gymnastics like English." },
  { id:"u3-14", unit:3, type:"p", hanzi:"我叫马杰", pinyin:"wǒ jiào mǎ jié", en:"my name is Matej", note:"马杰 (Mǎjié) — your Chinese name. Wear it proudly." },
  { id:"u3-15", unit:3, type:"p", hanzi:"你是哪国人？", pinyin:"nǐ shì nǎ guó rén", en:"which country are you from?" },
  { id:"u3-16", unit:3, type:"p", hanzi:"我是澳大利亚人", pinyin:"wǒ shì ào dà lì yà rén", en:"I'm Australian" },
  { id:"u3-17", unit:3, type:"p", hanzi:"很高兴认识你", pinyin:"hěn gāo xìng rèn shi nǐ", en:"nice to meet you" },
  { id:"u3-18", unit:3, type:"p", hanzi:"我二十岁", pinyin:"wǒ èr shí suì", en:"I'm twenty years old" },

  // ── Unit 4 · Family & Friends ─────────────────────────────────────
  { id:"u4-1",  unit:4, type:"w", hanzi:"家",   pinyin:"jiā",  en:"home / family" },
  { id:"u4-2",  unit:4, type:"w", hanzi:"爸爸", pinyin:"bà ba", en:"dad" },
  { id:"u4-3",  unit:4, type:"w", hanzi:"妈妈", pinyin:"mā ma", en:"mom" },
  { id:"u4-4",  unit:4, type:"w", hanzi:"哥哥", pinyin:"gē ge", en:"older brother" },
  { id:"u4-5",  unit:4, type:"w", hanzi:"姐姐", pinyin:"jiě jie", en:"older sister" },
  { id:"u4-6",  unit:4, type:"w", hanzi:"弟弟", pinyin:"dì di", en:"younger brother" },
  { id:"u4-7",  unit:4, type:"w", hanzi:"妹妹", pinyin:"mèi mei", en:"younger sister" },
  { id:"u4-8",  unit:4, type:"w", hanzi:"朋友", pinyin:"péng you", en:"friend" },
  { id:"u4-9",  unit:4, type:"w", hanzi:"有",   pinyin:"yǒu",  en:"to have" },
  { id:"u4-10", unit:4, type:"w", hanzi:"没有", pinyin:"méi yǒu", en:"to not have", note:"有 is special: negate it with 没, never 不." },
  { id:"u4-11", unit:4, type:"w", hanzi:"谁",   pinyin:"shéi", en:"who" },
  { id:"u4-12", unit:4, type:"w", hanzi:"的",   pinyin:"de",   en:"'s (possessive)", note:"我的 = my, 你的 = your. The glue of ownership." },
  { id:"u4-13", unit:4, type:"p", hanzi:"这是我的朋友", pinyin:"zhè shì wǒ de péng you", en:"this is my friend" },
  { id:"u4-14", unit:4, type:"p", hanzi:"你有兄弟姐妹吗？", pinyin:"nǐ yǒu xiōng dì jiě mèi ma", en:"do you have siblings?" },
  { id:"u4-15", unit:4, type:"p", hanzi:"我有一个哥哥", pinyin:"wǒ yǒu yí ge gē ge", en:"I have an older brother" },
  { id:"u4-16", unit:4, type:"p", hanzi:"我爱你", pinyin:"wǒ ài nǐ", en:"I love you" },

  // ── Unit 5 · This & That ──────────────────────────────────────────
  { id:"u5-1",  unit:5, type:"w", hanzi:"这",   pinyin:"zhè",  en:"this" },
  { id:"u5-2",  unit:5, type:"w", hanzi:"那",   pinyin:"nà",   en:"that" },
  { id:"u5-3",  unit:5, type:"w", hanzi:"个",   pinyin:"gè",   en:"(measure word)", note:"Chinese counts with measure words. 个 is the universal one: 一个人 = one person." },
  { id:"u5-4",  unit:5, type:"w", hanzi:"东西", pinyin:"dōng xi", en:"thing / stuff" },
  { id:"u5-5",  unit:5, type:"w", hanzi:"手机", pinyin:"shǒu jī", en:"phone", note:"Literally “hand machine”. Chinese loves compound logic." },
  { id:"u5-6",  unit:5, type:"w", hanzi:"电脑", pinyin:"diàn nǎo", en:"computer", note:"Literally “electric brain” 🧠⚡" },
  { id:"u5-7",  unit:5, type:"w", hanzi:"书",   pinyin:"shū",  en:"book" },
  { id:"u5-8",  unit:5, type:"w", hanzi:"水",   pinyin:"shuǐ", en:"water" },
  { id:"u5-9",  unit:5, type:"w", hanzi:"钱",   pinyin:"qián", en:"money" },
  { id:"u5-10", unit:5, type:"p", hanzi:"这是什么？", pinyin:"zhè shì shén me", en:"what is this?", note:"Your #1 vocabulary-mining tool in China. Point and ask." },
  { id:"u5-11", unit:5, type:"p", hanzi:"那是我的手机", pinyin:"nà shì wǒ de shǒu jī", en:"that is my phone" },
  { id:"u5-12", unit:5, type:"w", hanzi:"这个", pinyin:"zhè ge", en:"this one" },
  { id:"u5-13", unit:5, type:"w", hanzi:"那个", pinyin:"nà ge", en:"that one" },
  { id:"u5-14", unit:5, type:"w", hanzi:"我的", pinyin:"wǒ de", en:"my / mine" },

  // ── Unit 6 · Food & Drink ─────────────────────────────────────────
  { id:"u6-1",  unit:6, type:"w", hanzi:"吃",   pinyin:"chī",  en:"to eat" },
  { id:"u6-2",  unit:6, type:"w", hanzi:"喝",   pinyin:"hē",   en:"to drink" },
  { id:"u6-3",  unit:6, type:"w", hanzi:"米饭", pinyin:"mǐ fàn", en:"rice" },
  { id:"u6-4",  unit:6, type:"w", hanzi:"面条", pinyin:"miàn tiáo", en:"noodles" },
  { id:"u6-5",  unit:6, type:"w", hanzi:"茶",   pinyin:"chá",  en:"tea" },
  { id:"u6-6",  unit:6, type:"w", hanzi:"咖啡", pinyin:"kā fēi", en:"coffee" },
  { id:"u6-7",  unit:6, type:"w", hanzi:"啤酒", pinyin:"pí jiǔ", en:"beer" },
  { id:"u6-8",  unit:6, type:"w", hanzi:"好吃", pinyin:"hǎo chī", en:"delicious", note:"Literally “good-eat”. For drinks say 好喝 (good-drink)." },
  { id:"u6-9",  unit:6, type:"w", hanzi:"饿",   pinyin:"è",    en:"hungry" },
  { id:"u6-10", unit:6, type:"w", hanzi:"要",   pinyin:"yào",  en:"to want" },
  { id:"u6-11", unit:6, type:"w", hanzi:"想",   pinyin:"xiǎng", en:"would like to", note:"想 is softer than 要. 我想… = I'd like to…" },
  { id:"u6-12", unit:6, type:"w", hanzi:"服务员", pinyin:"fú wù yuán", en:"waiter / server", note:"Call this out in a restaurant to get attention. Totally normal!" },
  { id:"u6-13", unit:6, type:"w", hanzi:"菜单", pinyin:"cài dān", en:"menu" },
  { id:"u6-14", unit:6, type:"w", hanzi:"买单", pinyin:"mǎi dān", en:"the bill, please" },
  { id:"u6-15", unit:6, type:"p", hanzi:"我要一杯咖啡", pinyin:"wǒ yào yì bēi kā fēi", en:"I want a cup of coffee" },
  { id:"u6-16", unit:6, type:"p", hanzi:"我饿了", pinyin:"wǒ è le", en:"I'm hungry", note:"了 signals a new state: I wasn't hungry, now I am." },
  { id:"u6-17", unit:6, type:"p", hanzi:"太好吃了", pinyin:"tài hǎo chī le", en:"so delicious!", note:"太…了 = “too/so …!” Your compliment formula." },
  { id:"u6-18", unit:6, type:"w", hanzi:"干杯", pinyin:"gān bēi", en:"cheers!", note:"Literally “dry the cup”. Use responsibly 🍻" },

  // ── Unit 7 · Time ─────────────────────────────────────────────────
  { id:"u7-1",  unit:7, type:"w", hanzi:"今天", pinyin:"jīn tiān", en:"today" },
  { id:"u7-2",  unit:7, type:"w", hanzi:"明天", pinyin:"míng tiān", en:"tomorrow" },
  { id:"u7-3",  unit:7, type:"w", hanzi:"昨天", pinyin:"zuó tiān", en:"yesterday" },
  { id:"u7-4",  unit:7, type:"w", hanzi:"现在", pinyin:"xiàn zài", en:"now" },
  { id:"u7-5",  unit:7, type:"w", hanzi:"点",   pinyin:"diǎn", en:"o'clock" },
  { id:"u7-6",  unit:7, type:"w", hanzi:"星期", pinyin:"xīng qī", en:"week" },
  { id:"u7-7",  unit:7, type:"w", hanzi:"月",   pinyin:"yuè",  en:"month / moon" },
  { id:"u7-8",  unit:7, type:"w", hanzi:"年",   pinyin:"nián", en:"year" },
  { id:"u7-9",  unit:7, type:"w", hanzi:"上午", pinyin:"shàng wǔ", en:"morning (a.m.)" },
  { id:"u7-10", unit:7, type:"w", hanzi:"下午", pinyin:"xià wǔ", en:"afternoon" },
  { id:"u7-11", unit:7, type:"w", hanzi:"晚上", pinyin:"wǎn shang", en:"evening / night" },
  { id:"u7-12", unit:7, type:"w", hanzi:"时间", pinyin:"shí jiān", en:"time" },
  { id:"u7-13", unit:7, type:"p", hanzi:"现在几点？", pinyin:"xiàn zài jǐ diǎn", en:"what time is it?" },
  { id:"u7-14", unit:7, type:"p", hanzi:"现在三点", pinyin:"xiàn zài sān diǎn", en:"it's three o'clock", note:"No “is” needed for time. Now three o'clock. Done." },
  { id:"u7-15", unit:7, type:"p", hanzi:"今天星期几？", pinyin:"jīn tiān xīng qī jǐ", en:"what day is it today?" },
  { id:"u7-16", unit:7, type:"p", hanzi:"我没有时间", pinyin:"wǒ méi yǒu shí jiān", en:"I don't have time" },

  // ── Unit 8 · Getting Around ───────────────────────────────────────
  { id:"u8-1",  unit:8, type:"w", hanzi:"哪里", pinyin:"nǎ lǐ", en:"where" },
  { id:"u8-2",  unit:8, type:"w", hanzi:"这里", pinyin:"zhè lǐ", en:"here" },
  { id:"u8-3",  unit:8, type:"w", hanzi:"那里", pinyin:"nà lǐ", en:"there" },
  { id:"u8-4",  unit:8, type:"w", hanzi:"去",   pinyin:"qù",   en:"to go" },
  { id:"u8-5",  unit:8, type:"w", hanzi:"来",   pinyin:"lái",  en:"to come" },
  { id:"u8-6",  unit:8, type:"w", hanzi:"在",   pinyin:"zài",  en:"at / to be in", note:"Location word: 我在家 = I'm at home." },
  { id:"u8-7",  unit:8, type:"w", hanzi:"厕所", pinyin:"cè suǒ", en:"toilet" },
  { id:"u8-8",  unit:8, type:"w", hanzi:"饭店", pinyin:"fàn diàn", en:"restaurant" },
  { id:"u8-9",  unit:8, type:"w", hanzi:"商店", pinyin:"shāng diàn", en:"shop" },
  { id:"u8-10", unit:8, type:"w", hanzi:"机场", pinyin:"jī chǎng", en:"airport" },
  { id:"u8-11", unit:8, type:"w", hanzi:"火车站", pinyin:"huǒ chē zhàn", en:"train station", note:"Literally “fire-cart station” 🚂" },
  { id:"u8-12", unit:8, type:"w", hanzi:"出租车", pinyin:"chū zū chē", en:"taxi" },
  { id:"u8-13", unit:8, type:"w", hanzi:"左",   pinyin:"zuǒ",  en:"left" },
  { id:"u8-14", unit:8, type:"w", hanzi:"右",   pinyin:"yòu",  en:"right" },
  { id:"u8-15", unit:8, type:"w", hanzi:"远",   pinyin:"yuǎn", en:"far" },
  { id:"u8-16", unit:8, type:"w", hanzi:"近",   pinyin:"jìn",  en:"near" },
  { id:"u8-17", unit:8, type:"p", hanzi:"厕所在哪里？", pinyin:"cè suǒ zài nǎ lǐ", en:"where is the toilet?", note:"Pattern: [thing] 在哪里? Works for literally anything you're looking for." },
  { id:"u8-18", unit:8, type:"p", hanzi:"我去机场", pinyin:"wǒ qù jī chǎng", en:"I'm going to the airport" },

  // ── Unit 9 · Shopping ─────────────────────────────────────────────
  { id:"u9-1",  unit:9, type:"w", hanzi:"买",   pinyin:"mǎi",  en:"to buy", note:"买 mǎi (3rd, dip) = buy. 卖 mài (4th, drop) = sell. Tones = money." },
  { id:"u9-2",  unit:9, type:"w", hanzi:"卖",   pinyin:"mài",  en:"to sell" },
  { id:"u9-3",  unit:9, type:"w", hanzi:"块",   pinyin:"kuài", en:"yuan (money)" },
  { id:"u9-4",  unit:9, type:"w", hanzi:"贵",   pinyin:"guì",  en:"expensive" },
  { id:"u9-5",  unit:9, type:"w", hanzi:"便宜", pinyin:"pián yi", en:"cheap" },
  { id:"u9-6",  unit:9, type:"w", hanzi:"可以", pinyin:"kě yǐ", en:"can / may" },
  { id:"u9-7",  unit:9, type:"w", hanzi:"行",   pinyin:"xíng", en:"OK / that works" },
  { id:"u9-8",  unit:9, type:"w", hanzi:"不行", pinyin:"bù xíng", en:"no way / not OK" },
  { id:"u9-9",  unit:9, type:"w", hanzi:"一点", pinyin:"yì diǎn", en:"a little" },
  { id:"u9-10", unit:9, type:"p", hanzi:"多少钱？", pinyin:"duō shao qián", en:"how much is it?" },
  { id:"u9-11", unit:9, type:"p", hanzi:"太贵了", pinyin:"tài guì le", en:"too expensive!", note:"Step one of every good haggle." },
  { id:"u9-12", unit:9, type:"p", hanzi:"便宜一点，好吗？", pinyin:"pián yi yì diǎn hǎo ma", en:"a bit cheaper, OK?" },
  { id:"u9-13", unit:9, type:"p", hanzi:"我买这个", pinyin:"wǒ mǎi zhè ge", en:"I'll buy this one" },
  { id:"u9-14", unit:9, type:"p", hanzi:"可以吗？", pinyin:"kě yǐ ma", en:"may I? / is that OK?" },

  // ── Unit 10 · Daily Life ──────────────────────────────────────────
  { id:"u10-1",  unit:10, type:"w", hanzi:"做",   pinyin:"zuò",  en:"to do / to make" },
  { id:"u10-2",  unit:10, type:"w", hanzi:"看",   pinyin:"kàn",  en:"to look / to watch" },
  { id:"u10-3",  unit:10, type:"w", hanzi:"听",   pinyin:"tīng", en:"to listen" },
  { id:"u10-4",  unit:10, type:"w", hanzi:"说",   pinyin:"shuō", en:"to speak / to say" },
  { id:"u10-5",  unit:10, type:"w", hanzi:"工作", pinyin:"gōng zuò", en:"work / job" },
  { id:"u10-6",  unit:10, type:"w", hanzi:"学习", pinyin:"xué xí", en:"to study" },
  { id:"u10-7",  unit:10, type:"w", hanzi:"睡觉", pinyin:"shuì jiào", en:"to sleep" },
  { id:"u10-8",  unit:10, type:"w", hanzi:"起床", pinyin:"qǐ chuáng", en:"to get up" },
  { id:"u10-9",  unit:10, type:"w", hanzi:"喜欢", pinyin:"xǐ huan", en:"to like" },
  { id:"u10-10", unit:10, type:"w", hanzi:"爱",   pinyin:"ài",   en:"to love" },
  { id:"u10-11", unit:10, type:"w", hanzi:"会",   pinyin:"huì",  en:"can (know how to)", note:"会 = learned skills. 我会说中文 = I can speak Chinese." },
  { id:"u10-12", unit:10, type:"w", hanzi:"走",   pinyin:"zǒu",  en:"to walk / to leave" },
  { id:"u10-13", unit:10, type:"p", hanzi:"我会说一点中文", pinyin:"wǒ huì shuō yì diǎn zhōng wén", en:"I can speak a little Chinese", note:"The sentence that makes every conversation in China 10× friendlier." },
  { id:"u10-14", unit:10, type:"p", hanzi:"你喜欢什么？", pinyin:"nǐ xǐ huan shén me", en:"what do you like?" },
  { id:"u10-15", unit:10, type:"p", hanzi:"我喜欢喝茶", pinyin:"wǒ xǐ huan hē chá", en:"I like drinking tea" },
  { id:"u10-16", unit:10, type:"p", hanzi:"我在工作", pinyin:"wǒ zài gōng zuò", en:"I'm working", note:"在 + verb = the “-ing” of Chinese." },

  // ── Unit 11 · Feelings ────────────────────────────────────────────
  { id:"u11-1",  unit:11, type:"w", hanzi:"累",   pinyin:"lèi",  en:"tired" },
  { id:"u11-2",  unit:11, type:"w", hanzi:"忙",   pinyin:"máng", en:"busy" },
  { id:"u11-3",  unit:11, type:"w", hanzi:"开心", pinyin:"kāi xīn", en:"happy", note:"Literally “open heart” 💛" },
  { id:"u11-4",  unit:11, type:"w", hanzi:"热",   pinyin:"rè",   en:"hot" },
  { id:"u11-5",  unit:11, type:"w", hanzi:"冷",   pinyin:"lěng", en:"cold" },
  { id:"u11-6",  unit:11, type:"w", hanzi:"太",   pinyin:"tài",  en:"too / so" },
  { id:"u11-7",  unit:11, type:"w", hanzi:"非常", pinyin:"fēi cháng", en:"very / extremely" },
  { id:"u11-8",  unit:11, type:"w", hanzi:"有点", pinyin:"yǒu diǎn", en:"a bit (negative)", note:"有点 flavors complaints: 有点累 = a bit tired." },
  { id:"u11-9",  unit:11, type:"w", hanzi:"怎么样", pinyin:"zěn me yàng", en:"how is it? / how about it?" },
  { id:"u11-10", unit:11, type:"w", hanzi:"还可以", pinyin:"hái kě yǐ", en:"not bad / alright" },
  { id:"u11-11", unit:11, type:"p", hanzi:"真的吗？", pinyin:"zhēn de ma", en:"really?!" },
  { id:"u11-12", unit:11, type:"w", hanzi:"没问题", pinyin:"méi wèn tí", en:"no problem" },
  { id:"u11-13", unit:11, type:"p", hanzi:"我很累", pinyin:"wǒ hěn lèi", en:"I'm so tired", note:"Adjectives don't need “is”: 我累 not 我是累. 很 fills the rhythm." },
  { id:"u11-14", unit:11, type:"p", hanzi:"今天很热", pinyin:"jīn tiān hěn rè", en:"it's hot today" },
  { id:"u11-15", unit:11, type:"p", hanzi:"你怎么样？", pinyin:"nǐ zěn me yàng", en:"how are you doing?", note:"More natural than 你好吗 between friends." },
  { id:"u11-16", unit:11, type:"w", hanzi:"加油", pinyin:"jiā yóu", en:"you got this! / let's go!", note:"Literally “add oil”. China's universal cheer 📣" },

  // ── Unit 12 · Conversation Glue ───────────────────────────────────
  { id:"u12-1",  unit:12, type:"w", hanzi:"吗",   pinyin:"ma",   en:"(yes/no question word)", note:"Statement + 吗 = question. 好 → 好吗? Easiest grammar ever." },
  { id:"u12-2",  unit:12, type:"w", hanzi:"呢",   pinyin:"ne",   en:"what about…?", note:"我很好，你呢？ = I'm good, what about you?" },
  { id:"u12-3",  unit:12, type:"w", hanzi:"也",   pinyin:"yě",   en:"also" },
  { id:"u12-4",  unit:12, type:"w", hanzi:"都",   pinyin:"dōu",  en:"all / both" },
  { id:"u12-5",  unit:12, type:"w", hanzi:"和",   pinyin:"hé",   en:"and / with" },
  { id:"u12-6",  unit:12, type:"w", hanzi:"但是", pinyin:"dàn shì", en:"but" },
  { id:"u12-7",  unit:12, type:"w", hanzi:"因为", pinyin:"yīn wèi", en:"because" },
  { id:"u12-8",  unit:12, type:"w", hanzi:"所以", pinyin:"suǒ yǐ", en:"so / therefore" },
  { id:"u12-9",  unit:12, type:"w", hanzi:"对",   pinyin:"duì",  en:"correct / right", note:"对对对 — you'll hear this rapid-fire agreement everywhere." },
  { id:"u12-10", unit:12, type:"w", hanzi:"当然", pinyin:"dāng rán", en:"of course" },
  { id:"u12-11", unit:12, type:"p", hanzi:"我不懂", pinyin:"wǒ bù dǒng", en:"I don't understand", note:"Your safety net. Say it early, say it often." },
  { id:"u12-12", unit:12, type:"p", hanzi:"我懂了", pinyin:"wǒ dǒng le", en:"I get it now" },
  { id:"u12-13", unit:12, type:"p", hanzi:"请再说一遍", pinyin:"qǐng zài shuō yí biàn", en:"please say that again" },
  { id:"u12-14", unit:12, type:"p", hanzi:"慢一点", pinyin:"màn yì diǎn", en:"slower, please" },
  { id:"u12-15", unit:12, type:"p", hanzi:"你说什么？", pinyin:"nǐ shuō shén me", en:"what did you say?" },
  { id:"u12-16", unit:12, type:"w", hanzi:"没事", pinyin:"méi shì", en:"it's nothing / no worries" },
];
